"""Spectral utilities and model helpers."""

from __future__ import annotations

from .model_atmospheres import (
    apply_broadening,
    broadening,
    convert_flux_density,
    convert_to_physical,
    fnu_to_flam,
    interpolate_model_grid,
    interpolate,
    interpolate_linear,
    interpolate_to_linear_wavelength,
    load_atmosphere_grid,
    load_models,
    load_tremblay_grid,
    plot_line_fits,
    plot_line_profile_fits,
    scale_model_flux,
)
from .binary_system import (
    calculate_logg,
    calculate_radius,
    calculate_rv,
    gauss_prob,
    gaussian_log_probability,
    inclination_from_cosi,
    log_surface_gravity,
    roche_lobe_radius,
    secondary_rv_semiamplitude,
)
from .spectral_analysis import (
    BJDConvert,
    clip_outliers,
    doppler_shift_wavelength,
    extract_lines,
    extract_line_windows,
    estimate_resolution_from_wavelength_grid,
    fit_teff_logg_grid,
    line_model,
    linear_model,
    model_flux_for_solution,
    multi_voigt_lines,
    normalize_continuum,
    read_hst_stis_spectrum,
    shift_wavelength,
    sigma_clip_outliers,
    voigt_line_with_continuum,
)

__all__ = [
    "BJDConvert",
    "apply_broadening",
    "broadening",
    "calculate_logg",
    "calculate_radius",
    "calculate_rv",
    "clip_outliers",
    "convert_flux_density",
    "convert_to_physical",
    "doppler_shift_wavelength",
    "extract_lines",
    "extract_line_windows",
    "estimate_resolution_from_wavelength_grid",
    "fit_teff_logg_grid",
    "fnu_to_flam",
    "gauss_prob",
    "gaussian_log_probability",
    "inclination_from_cosi",
    "interpolate",
    "interpolate_linear",
    "interpolate_model_grid",
    "interpolate_to_linear_wavelength",
    "line_model",
    "linear_model",
    "load_atmosphere_grid",
    "load_models",
    "load_tremblay_grid",
    "log_surface_gravity",
    "multi_voigt_lines",
    "model_flux_for_solution",
    "normalize_continuum",
    "plot_line_fits",
    "plot_line_profile_fits",
    "roche_lobe_radius",
    "read_hst_stis_spectrum",
    "scale_model_flux",
    "secondary_rv_semiamplitude",
    "shift_wavelength",
    "sigma_clip_outliers",
    "voigt_line_with_continuum",
]
